### ISSUE TITLE
Add favicon/Apple Touch Icon

### ISSUE THREAD

**Issue by BK1096** [dani3l0/honey#7]
Good evening,

How would I go about adding an Apple Touch Icon to this webpage for when I save the site to my iPhone home page? I'm new to HTML so I apologize if this was the wrong medium to bring this up.

Thank you!

**Comment by dani3l0** [comment]
I don't use iPhones nor other Apple devices :<, but ig it's doable

**Comment by dani3l0** [comment]
Lemme know if that helped :eyes:

**Comment by dani3l0** [comment]
ig we can close this :thinking:

**Comment by BK1096** [comment]
Sorry for the delay. Yes that worked, thank you!
